messages:
  join:
    top: "&c&lFire&6&lstar&e&lter"
    bottom: "&rWelcome back."
  death:
    top: "&c&lF"
    bottom: "&6/back to return to your death location."
  beehive: "&6%s bees"

tablist:
  header: "&r \n&c&lFire&6&lstar&e&lter\n&7&oSurvival Realm\n&r \n&7&oOnline players: %s"
  footer: "&r \n&7Join the Discord! &b/discord\n&r "
  priority:
    - admin
    - mod
    - spark
    - default
  teams:
    admin:
      color: "RED"
      prefix: "&c[Admin] "
    mod:
      color: "GOLD"
      prefix: "&6[Mod] "
    spark:
      color: "YELLOW"
      prefix: ""
    default:
      color: "RESET"
      prefix: ""

wild:
  cooldown: 5
  world: "world"
  min:
    x: -3125
    z: -3125
  max:
    x: 3125
    z: 3125
  title:
    finding:
      top: "&6&lLooking for a location..."
      bottom: "&rHang tight until you arrive."
    teleported:
      top: "&6&lWelcome... home?"
      bottom: "&rYou've arrived at an uninhabited location."
    cooldown:
      top: "&c&lCan't teleport just yet."
      bottom: "&rWait [minutes] more minute(s)."

playtime:
  60:
    name: "camper"
    commands:
      - "lp user [player] parent add camper"
      - "eco give [player] 100"
  1440:
    name: "pioneer"
    commands:
      - "lp user [player] parent add pioneer"
      - "eco give [player] 500"
  5760:
    name: "vanguard"
    commands:
      - "lp user [player] parent add vanguard"
      - "eco give [player] 1000"

ranks:
  scout:
    - "&aDefault rank"
    - "&71 job slot"
    - "&79 pet slots"
  camper:
    - "&7Playtime: &b1 hour"
    - "&72 job slot"
    - "&718 pet slots"
    - "&a+ $100"
  pioneer:
    - "&7Playtime: &b1 day"
    - "&73 job slot"
    - "&727 pet slots"
    - "&a+ $500"
  vanguard:
    - "&7Playtime: &b5 days"
    - "&75 job slot"
    - "&736 pet slots"
    - "&a+ $1,000"
  spark:
    - "&dDonor rank"
    - "&7All Vanguard rewards"
    - "&f+ extras (use /buy)"

webhooks:
  notifications: ""
  moderation: ""

perks:
  potions:
    SPEED:
      item: FEATHER
      level: 2
      name: "&f&lSpeed"
      lore: "&7Speed II"