messages:
  join:
    top: "&c&lFire&6&lstar&e&lter"
    bottom: "&rWelcome back."
  death:
    top: "&c&lF"
    bottom: "&6/back to return to your death location."
  beehive: "&6%s bees"

tablist:
  header: "&r \n&c&lFire&6&lstar&e&lter\n&7&oSurvival Realm\n&r \n&7&oOnline players: [online]"
  footer: "&r \n&7Join the Discord! &b/discord\n&r "
  priority:
    - admin
    - mod
    - spark
    - default
  groups:
    admin:
      color: "RED"
      prefix: "&c[Admin] "
    mod:
      color: "GOLD"
      prefix: "&6[Mod] "
    spark:
      color: "YELLOW"
      prefix: ""
    default:
      color: "RESET"
      prefix: ""

wild:
  cooldown: 5
  world: "world"
  min:
    x: -3125
    z: -3125
  max:
    x: 3125
    z: 3125
  title:
    finding:
      top: "&6&lLooking for a location..."
      bottom: "&7Hang tight until you arrive."
    teleported:
      top: "&6&lWelcome... home?"
      bottom: "&7You've arrived at an uninhabited location."
    cooldown:
      top: "&c&lCan't teleport just yet."
      bottom: "&7Wait [minutes] more minute(s)."
    queue:
      top: "&d&lQueue limit."
      bottom: "&7Looks like teleporting failed :/"
    error:
      top: "&c&lWelp, that failed."
      bottom: "&7Looks like teleporting failed :/"