name: Wildfire
version: 1.4
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Wildfire.Wildfire
description: The core for Firestarter servers!
api-version: 1.15
depend: [Kerosene, GriefPrevention, Essentials]

commands:
  wildfire:
    description: "Base command for Wildfire!"
  rtp:
    description: "Randomly teleport somewhere in the world!"
    aliases: ['wild']
  claim:
    description: "Obtain your very own claim kit!"
  skull:
    description: "Obtain a custom player head of your choosing!"

permissions:
  firestarter.features.skull:
    default: op