name: Campfire
version: 3.1
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Campfire.Campfire
description: Firestarter's package of basic server utilities.
website: https://firestartermc.com/opensource
api-version: 1.15
depend: ['Kerosene', 'GriefPrevention']

commands:
  campfire:
    description: "Base Campfire management command."
  colorcodes:
    description: "View all of the usable in-game color codes."
    aliases: ['colors', 'color']
  wild:
    description: "Teleport to a random location in the world."
    aliases: ['rtp', 'wildtp']
  toggle:
    description: "Toggle various features of the server."
    aliases: ['toggles', 'change', 'switch', 'enable', 'disable']
  #perks:
  #  description: "View and manage your donor perks."
  #  aliases: ['donor', 'spark']
  playtime:
    description: "View your total playtime on the server."
    aliases: ["joined", "played", "timeplayed"]
  pvp:
    description: "Toggle your PvP state."
  ranks:
    description: "View all of our ranks on the server."
    aliases: ['rank']
  setslots:
    description: "Adjust the maximum player slot count while the server is running."
    permission: "campfire.admin"
  #vanish:
  #  description: "Vanish from online players."
  #  aliases: ['v']
  #  permission: "firestarter.vanish"

permissions:
  campfire.perk.potions:
    default: op
  campfire.admin:
    default: op