name: "Campfire"
description: "A collection of basic utilities and administrative utilities."
main: "com.firestartermc.campfire.Campfire"
author: "Firestarter Minecraft Servers"
website: "https://firestartermc.com"
version: "5.0"
api-version: "1.16"

depend:
  - "Kerosene"

softdepend:
  - "GriefPrevention"
  - "Chairs"

commands:
  safeshutdown:
    description: "Shuts down the server after safely kicking all online players."
    permission: "firestarter.administrator"
  setslots:
    description: "Adjust the maximum slot count whilst the server is running."
    usage: "/<command> <slots>"
    permission: "firestarter.administrator"
  colorcodes:
    description: "View all of the usable in-game color codes."
    aliases: ['colors', 'color']
  report:
    description: "Report a player to the staff team with a reason."
  shoplog:
    description: "View the items that were sold from your shops while you were offline."

permissions:
  firestarter.administrator:
    default: op
  firestarter.staff:
    default: op
  campfire.staff:
    default: op
  campfire.admin:
    default: op