name: ${name}
version: Build ${version}
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.${name}.${name}
description: The core for Firestarter servers!
api-version: 1.14
depend: [Kerosene, ProtocolLib, GriefPrevention, Essentials]

commands:
  wildfire:
    description: "Base command for Wildfire!"
  rtp:
    description: "Randomly teleport somewhere in the world!"
    aliases: ['wild']
  claim:
    description: "Obtain your very own claim kit!"