name: "Campfire"
description: "A collection of basic utilities and survival extras."
main: "com.firestartermc.campfire.Campfire"
author: "Firestarter Minecraft Servers"
website: "https://firestartermc.com"
version: "5.0"
api-version: "1.16"

depend:
  - "Kerosene"

softdepend:
  - "GriefPrevention"
  - "Chairs"

commands:
  campfire:
    description: "Base Campfire management command."
  colorcodes:
    description: "View all of the usable in-game color codes."
    aliases: ['colors', 'color']
  report:
    description: "Report a player to the staff team with a reason."
  setslots:
    description: "Adjust the maximum player slot count while the server is running."
    permission: "campfire.admin"
  shoplog:
    description: "View the items that were sold from your shops while you were offline."

permissions:
  campfire.staff:
    default: op
  campfire.admin:
    default: op